export const LabelColors = [
  {
    id: 'light-green',
    bgColor: 'bg-green-200',
    bgHoverColor: 'hover:bg-green-300',
    iconColor: 'text-green-500',
    isActive: false,
  },
  {
    id: 'green',
    bgColor: 'bg-green-300',
    bgHoverColor: 'hover:bg-green-400',
    iconColor: 'text-green-600',
    isActive: false,
  },
  {
    id: 'dark-green',
    bgColor: 'bg-green-400',
    bgHoverColor: 'hover:bg-green-500',
    iconColor: 'text-green-700',
    isActive: false,
  },
  {
    id: 'light-blue',
    bgColor: 'bg-blue-200',
    bgHoverColor: 'hover:bg-blue-300',
    iconColor: 'text-blue-500',
    isActive: false,
  },
  {
    id: 'blue',
    bgColor: 'bg-blue-300',
    bgHoverColor: 'hover:bg-blue-400',
    iconColor: 'text-blue-600',
    isActive: false,
  },
  {
    id: 'dark-blue',
    bgColor: 'bg-blue-400',
    bgHoverColor: 'hover:bg-blue-500',
    iconColor: 'text-blue-700',
    isActive: false,
  },
  {
    id: 'light-yellow',
    bgColor: 'bg-yellow-200',
    bgHoverColor: 'hover:bg-yellow-300',
    iconColor: 'text-yellow-500',
    isActive: false,
  },
  {
    id: 'yellow',
    bgColor: 'bg-yellow-300',
    bgHoverColor: 'hover:bg-yellow-400',
    iconColor: 'text-yellow-600',
    isActive: false,
  },
  {
    id: 'dark-yellow',
    bgColor: 'bg-yellow-400',
    bgHoverColor: 'hover:bg-yellow-500',
    iconColor: 'text-yellow-700',
    isActive: false,
  },
  {
    id: 'light-sky',
    bgColor: 'bg-sky-200',
    bgHoverColor: 'hover:bg-sky-300',
    iconColor: 'text-sky-500',
    isActive: false,
  },
  {
    id: 'sky',
    bgColor: 'bg-sky-300',
    bgHoverColor: 'hover:bg-sky-400',
    iconColor: 'text-sky-600',
    isActive: false,
  },
  {
    id: 'dark-sky',
    bgColor: 'bg-sky-400',
    bgHoverColor: 'hover:bg-sky-500',
    iconColor: 'text-sky-700',
    isActive: false,
  },
  {
    id: 'light-orange',
    bgColor: 'bg-orange-200',
    bgHoverColor: 'hover:bg-orange-300',
    iconColor: 'text-orange-500',
    isActive: false,
  },
  {
    id: 'orange',
    bgColor: 'bg-orange-300',
    bgHoverColor: 'hover:bg-orange-400',
    iconColor: 'text-orange-600',
    isActive: false,
  },
  {
    id: 'dark-orange',
    bgColor: 'bg-orange-400',
    bgHoverColor: 'hover:bg-orange-500',
    iconColor: 'text-orange-700',
    isActive: false,
  },
  {
    id: 'light-lime',
    bgColor: 'bg-lime-200',
    bgHoverColor: 'hover:bg-lime-300',
    iconColor: 'text-lime-500',
    isActive: false,
  },
  {
    id: 'lime',
    bgColor: 'bg-lime-300',
    bgHoverColor: 'hover:bg-lime-400',
    iconColor: 'text-lime-600',
    isActive: false,
  },
  {
    id: 'dark-lime',
    bgColor: 'bg-lime-400',
    bgHoverColor: 'hover:bg-lime-500',
    iconColor: 'text-lime-700',
    isActive: false,
  },
  {
    id: 'light-red',
    bgColor: 'bg-red-200',
    bgHoverColor: 'hover:bg-red-300',
    iconColor: 'text-red-500',
    isActive: false,
  },
  {
    id: 'red',
    bgColor: 'bg-red-300',
    bgHoverColor: 'hover:bg-red-400',
    iconColor: 'text-red-600',
    isActive: false,
  },
  {
    id: 'dark-red',
    bgColor: 'bg-red-400',
    bgHoverColor: 'hover:bg-red-500',
    iconColor: 'text-red-700',
    isActive: false,
  },
  {
    id: 'light-pink',
    bgColor: 'bg-pink-200',
    bgHoverColor: 'hover:bg-pink-300',
    iconColor: 'text-pink-500',
    isActive: false,
  },
  {
    id: 'pink',
    bgColor: 'bg-pink-300',
    bgHoverColor: 'hover:bg-pink-400',
    iconColor: 'text-pink-600',
    isActive: false,
  },
  {
    id: 'dark-pink',
    bgColor: 'bg-pink-400',
    bgHoverColor: 'hover:bg-red-500',
    iconColor: 'text-pink-700',
    isActive: false,
  },
  {
    id: 'light-purple',
    bgColor: 'bg-purple-200',
    bgHoverColor: 'hover:bg-purple-300',
    iconColor: 'text-purple-500',
    isActive: false,
  },
  {
    id: 'purple',
    bgColor: 'bg-purple-300',
    bgHoverColor: 'hover:bg-purple-400',
    iconColor: 'text-purple-600',
    isActive: false,
  },
  {
    id: 'dark-purple',
    bgColor: 'bg-purple-400',
    bgHoverColor: 'hover:bg-purple-500',
    iconColor: 'text-purple-700',
    isActive: false,
  },
  {
    id: 'light-dark',
    bgColor: 'bg-black opacity-30',
    bgHoverColor: 'hover:opacity-40',
    iconColor: 'text-green-500',
    isActive: false,
  },
  {
    id: 'dark',
    bgColor: 'bg-black opacity-40',
    bgHoverColor: 'hover:opacity-50',
    iconColor: 'text-green-500',
    isActive: false,
  },
  {
    id: 'dark-dark',
    bgColor: 'bg-black opacity-50',
    bgHoverColor: 'hover:opacity-60',
    iconColor: 'text-green-500',
    isActive: false,
  },
];
